
// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAKM4BeYLZ5zFl2S9ISGqLfkXczN8vIto',
    appId: '1:868312086400:web:a2b53bcdbe4f9524cbf365',
    messagingSenderId: '868312086400',
    projectId: 'candibean-android-app',
    authDomain: 'candibean-android-app.firebaseapp.com',
    databaseURL: 'https://candibean-android-app-default-rtdb.firebaseio.com',
    storageBucket: 'candibean-android-app.firebasestorage.app',
    measurementId: 'G-JMPHB2DP8G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApOTD-InRVl7C058tMryXxihh4ZKkvnFw',
    appId: '1:868312086400:android:17b6c66d153ba500cbf365',
    messagingSenderId: '868312086400',
    projectId: 'candibean-android-app',
    databaseURL: 'https://candibean-android-app-default-rtdb.firebaseio.com',
    storageBucket: 'candibean-android-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAKM4BeYLZ5zFl2S9ISGqLfkXczN8vIto',
    appId: '1:868312086400:ios:a2b53bcdbe4f9524cbf365',
    messagingSenderId: '868312086400',
    projectId: 'candibean-android-app',
    databaseURL: 'https://candibean-android-app-default-rtdb.firebaseio.com',
    storageBucket: 'candibean-android-app.appspot.com',
    iosBundleId: 'com.example.myapp',
  );
}